// GeBIZ opportunity crawler.
//
// GeBIZ publishes RSS for only a handful of procurement categories, and those
// feeds are empty most of the time — an audit on 11 Sep 2026 found 10 live
// feeds carrying 23 real tenders between them, with the main IT category
// empty. The tenders themselves are all on the site. This reads the site.
//
// It deliberately does not depend on GeBIZ's CSS class names, which are
// generated by their JSF framework and will change without warning. Instead it
// keys on the one thing we know is stable: every opportunity links to a detail
// page carrying a ?code= parameter, which is also the tender reference. Rows
// are then read out of whatever element contains that link.
//
// If it finds nothing it writes GeBIZ_Raw_diagnostic.txt describing what the
// page actually contained, so the selectors can be corrected from evidence
// rather than guessed at a second time.

import { chromium } from "playwright";
import { writeFile } from "node:fs/promises";

// Read off GeBIZ's own navigation after the first attempt returned their
// "Page not found" page for all three guessed paths.
const entryUrls = [
  "https://www.gebiz.gov.sg/ptn/opportunity/index.xhtml",
  "https://www.gebiz.gov.sg/ptn/opportunity/BOListing.xhtml?origin=menu",
  "https://www.gebiz.gov.sg/ptn/opportunity/opportunityListing.xhtml",
];
const output = "GeBIZ_Raw_latest.csv";
const statusOutput = "GeBIZ_Raw_status.json";
const diagnosticOutput = "GeBIZ_Raw_diagnostic.txt";
const maxPages = 20;

const csvCell = (value = "") => `"${String(value).replaceAll('"', '""')}"`;
const sgtStamp = () =>
  new Intl.DateTimeFormat("sv-SE", {
    timeZone: "Asia/Singapore",
    year: "numeric", month: "2-digit", day: "2-digit",
    hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false,
  }).format(new Date()).replace(" ", "T") + "+08:00";

// Runs inside the page. Everything it needs must be defined here.
const extractRows = () => {
  const DATE = /\d{1,2}\/\d{1,2}\/\d{4}(?:\s+\d{1,2}:\d{2}(?::\d{2})?)?/g;
  const clean = (value) => String(value || "").replace(/\s+/g, " ").trim();

  // The first ancestor carrying meaningfully more text than the link itself is
  // the row. Tables and list items are taken as rows outright.
  const rowOf = (anchor) => {
    const titleLength = clean(anchor.textContent).length;
    let node = anchor.parentElement;
    let fallback = null;
    for (let depth = 0; node && depth < 8; depth += 1) {
      const tag = node.tagName.toLowerCase();
      if (tag === "tr" || tag === "li") return node;
      const text = clean(node.innerText);
      if (!fallback && text.length > titleLength + 40) fallback = node;
      node = node.parentElement;
    }
    return fallback;
  };

  const anchors = Array.from(document.querySelectorAll('a[href*="code="]'));
  const rows = anchors.map((anchor) => {
    const href = anchor.href || "";
    const code = (href.match(/[?&]code=([^&]+)/i) || [])[1] || "";
    const row = rowOf(anchor);
    const rowText = clean(row ? row.innerText : anchor.textContent);
    const dates = rowText.match(DATE) || [];

    // Lines that are neither the title nor a date are candidates for agency
    // and category. GeBIZ lists the agency after the title.
    const title = clean(anchor.textContent);
    const lines = (row ? (row.innerText || "") : "")
      .split("\n").map(clean)
      .filter((line) => line && line !== title && !/^\d{1,2}\/\d{1,2}\/\d{4}/.test(line));

    return {
      reference: code ? decodeURIComponent(code) : "",
      title,
      agency: lines[0] || "",
      category: lines[1] || "",
      published: dates[0] || "",
      closing: dates[1] || "",
      link: href,
      rowText,
    };
  });

  return {
    rows: rows.filter((row) => row.title),
    diagnostic: {
      pageTitle: document.title,
      notFound: /page not found/i.test(document.title || ""),
      anchorsWithCode: anchors.length,
      totalAnchors: document.querySelectorAll("a").length,
      tables: document.querySelectorAll("table").length,
      rowCount: document.querySelectorAll("tr").length,
      forms: document.querySelectorAll("form").length,
      // A JSF listing often shows nothing until a search is submitted, so the
      // clickable controls are what matter when the page loads but is empty.
      buttons: Array.from(document.querySelectorAll("button, input[type=submit], a[role=button]"))
        .map((el) => clean(el.innerText || el.value || el.getAttribute("aria-label")))
        .filter(Boolean).slice(0, 20),
      sampleHrefs: Array.from(document.querySelectorAll("a"))
        .map((a) => a.getAttribute("href") || "").filter(Boolean).slice(0, 30),
      bodyText: clean(document.body ? document.body.innerText : "").slice(0, 3000),
    },
  };
};

const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1400 } });
page.setDefaultTimeout(45_000);

const records = [];
let pagesScanned = 0;
let usedUrl = "";
let lastDiagnostic = null;
const attempts = [];

try {
  // Try each known entry point until one actually lists opportunities.
  for (const url of entryUrls) {
    try {
      await page.goto(url, { waitUntil: "networkidle", timeout: 90_000 });
    } catch (error) {
      attempts.push({ url, error: String(error).slice(0, 200) });
      continue;
    }
    // Give the JSF page a moment to render its results table.
    await page.waitForTimeout(4000);
    let probe = await page.evaluate(extractRows);

    // The page may load fine and list nothing until a search is submitted.
    if (probe.rows.length === 0 && !probe.diagnostic.notFound) {
      const search = page
        .getByRole("button", { name: /search|find|go|submit/i })
        .or(page.locator('input[type="submit"][value*="earch" i]'))
        .first();
      if ((await search.count()) > 0) {
        try {
          await search.click({ timeout: 15_000 });
          await page.waitForTimeout(5000);
          probe = await page.evaluate(extractRows);
          probe.diagnostic.searchClicked = true;
        } catch {
          probe.diagnostic.searchClickFailed = true;
        }
      }
    }

    attempts.push({ url, ...probe.diagnostic, rowsFound: probe.rows.length });
    lastDiagnostic = { url, ...probe.diagnostic };
    if (probe.rows.length > 0) { usedUrl = url; records.push(...probe.rows); break; }
  }

  if (usedUrl) {
    pagesScanned = 1;
    // Paginate. GeBIZ uses a JSF paginator, so the control is found by role or
    // label rather than a class name that will not survive a redeploy.
    for (let pageNumber = 2; pageNumber <= maxPages; pageNumber += 1) {
      const next = page
        .locator('a[aria-label="Next Page"], a[title="Next"], button[aria-label="Next Page"]')
        .or(page.getByRole("link", { name: /^next$/i }))
        .first();
      if ((await next.count()) === 0) break;
      const before = records.length;
      try {
        await next.click({ timeout: 15_000 });
        await page.waitForTimeout(4000);
      } catch {
        break;
      }
      const probe = await page.evaluate(extractRows);
      const seen = new Set(records.map((record) => record.reference || record.title));
      const fresh = probe.rows.filter((row) => !seen.has(row.reference || row.title));
      if (fresh.length === 0) break; // Paginator did nothing; stop rather than loop.
      records.push(...fresh);
      pagesScanned = pageNumber;
      if (records.length === before) break;
    }
  }

  const unique = Array.from(new Map(records.map((record) =>
    [record.reference || `${record.title}|${record.agency}`, record])).values());

  if (unique.length === 0) {
    const dump = [
      `GeBIZ crawl found no opportunities — ${sgtStamp()}`,
      "",
      "This means the page structure assumption is wrong, not that GeBIZ is empty.",
      "Send this file back and the selectors can be corrected from it.",
      "",
      `Tried ${attempts.length} entry URL(s):`,
      JSON.stringify(attempts, null, 2),
    ].join("\n");
    await writeFile(diagnosticOutput, `${dump}\n`, "utf8");
    await writeFile(statusOutput, `${JSON.stringify({
      success: false,
      generated_at_sgt: sgtStamp(),
      records: 0,
      pages_scanned: pagesScanned,
      error: "no opportunity rows found — see GeBIZ_Raw_diagnostic.txt",
      source: lastDiagnostic ? lastDiagnostic.url : entryUrls[0],
    }, null, 2)}\n`, "utf8");
    // Still write an empty, well-formed CSV so the consumer never sees a 404.
    await writeFile(output, `${[
      "Tender/Ref No.", "Title", "Agency", "Procurement Category", "Source",
      "Scope Summary", "Publish Date/Time", "Closing Date/Time", "Status", "Link",
    ].map(csvCell).join(",")}\n`, "utf8");
    console.log(dump);
    throw new Error("GeBIZ rendered no opportunity rows — diagnostic written");
  }

  const header = [
    "Tender/Ref No.", "Title", "Agency", "Procurement Category", "Source",
    "Scope Summary", "Publish Date/Time", "Closing Date/Time", "Status", "Link",
  ];
  const lines = [header.map(csvCell).join(",")];
  for (const record of unique) {
    lines.push([
      record.reference, record.title, record.agency, record.category, "GeBIZ",
      // The whole row text is kept so nothing seen on the page is lost while
      // the field-level parsing is still being proven.
      record.rowText, record.published, record.closing, "Open", record.link,
    ].map(csvCell).join(","));
  }
  await writeFile(output, `${lines.join("\n")}\n`, "utf8");

  // A sample of raw rows every run, so drift in GeBIZ's markup shows up in the
  // artifact before it shows up as missing tenders in the tracker.
  await writeFile(diagnosticOutput, [
    `GeBIZ crawl OK — ${sgtStamp()}`,
    `Entry URL: ${usedUrl}`,
    `Rows: ${unique.length} across ${pagesScanned} page(s)`,
    "",
    "First 5 rows as parsed:",
    ...unique.slice(0, 5).map((record, index) =>
      `\n[${index + 1}] ref=${record.reference}\n    title=${record.title}\n`
      + `    agency=${record.agency}\n    category=${record.category}\n`
      + `    published=${record.published}  closing=${record.closing}\n`
      + `    raw=${record.rowText.slice(0, 300)}`),
  ].join("\n") + "\n", "utf8");

  const status = {
    success: true,
    generated_at_sgt: sgtStamp(),
    records: unique.length,
    pages_scanned: pagesScanned,
    source: usedUrl,
  };
  await writeFile(statusOutput, `${JSON.stringify(status, null, 2)}\n`, "utf8");
  console.log(JSON.stringify({ ...status, output, statusOutput }));
} finally {
  await browser.close();
}
